# Site
title:              Zack's Blog
bio:                'Step forward everyday to achieve a great goal.'
author:             Zack Ku
description:        "记录成长点滴，以汇聚成江河."
reading_time:       false
words_per_minute:   200
# logo:               'http://oboi2pfvn.bkt.clouddn.com/logo_me.jpg'
# background:         'http://oboi2pfvn.bkt.clouddn.com/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                http://starYellow966.github.io
# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        zackku
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              star96_huang@163.com
#twitter:            username
#facebook:           username
github:             zack-ku
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
